Web chia se tai lieu/Web chia se tai lieu/Controllers/ACategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.IdentityModel.Tokens;
using System.Reflection;
using Web_chia_se_tai_lieu.Models;
using System.Data.SqlClient;
namespace Web_chia_se_tai_lieu.Controllers
{
    public class ACategoryController : Controller
    {
        private readonly WebtailieuContext _context;

      
        

        public ACategoryController (WebtailieuContext context)
        {
            _context = context;
        }
        public  IActionResult Index()
        {
            
                List<Category> categories = _context.Categories.ToList();
                foreach(var category in categories)
            {
                category.NumberOfProduct = _context.Products.Where(p => p.CategoryId == category.Id).Count();
            }
                _context.SaveChanges();
                return View(categories);
                   
        }

        public IActionResult Add()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Add (Category category, IFormFile Image)
        {
            if (Image != null)
            {
                category.Image = SaveImage(Image);
            }
            else category.Image = "";
            
            category.NumberOfProduct = 0;
            
            _context.Categories.Add(category);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index)) ;
        }

        public IActionResult Edit()
        {
            return View();
        }

        public string SaveImage (IFormFile Image)
        {
            var savePath = Path.Combine("wwwroot/Images", Image.FileName);
            using(var fileStream = new FileStream(savePath, FileMode.Create))
            {
                Image.CopyTo(fileStream);
            }
            return "/Images/" + Image.FileName;
        }

        public IActionResult Delete(int id)
        {
            var category = _context.Categories.FirstOrDefault(c => c.Id == id);
            return View(category);
        }
        [HttpPost, ActionName("DeleteConfirm")]
        public IActionResult DeleteConfirm(int id)
        {
            var category = _context.Categories.FirstOrDefault(p => p.Id == id);
            _context.Categories.Remove(category);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index)) ;
        }
    }
}

Web chia se tai lieu/Web chia se tai lieu/Controllers/AProductController.cs
using Microsoft.AspNetCore.Connections;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Web_chia_se_tai_lieu.Models;
using System.IO;
using System.Text;
using System.Security.Cryptography;
using Web_chia_se_tai_lieu.ViewModels;

namespace Web_chia_se_tai_lieu.Controllers
{
    public class AProductController : Controller
    {
        private readonly WebtailieuContext _context;
        


        public AProductController(WebtailieuContext context)
        {
            _context = context;
        }
        public string MaHoaMatKhau(string password)
        {
            UnicodeEncoding encoding = new UnicodeEncoding();
            Byte[] hashBytes = encoding.GetBytes(password);
            SHA1CryptoServiceProvider sha1 = new SHA1CryptoServiceProvider();
            Byte[] cryptPassword = sha1.ComputeHash(hashBytes);
            return BitConverter.ToString(cryptPassword);
        }
        public IActionResult Register(string? str)
        {
            var categories = _context.Categories.ToList();
            categories.Sort((x, y) => x.Name.CompareTo(y.Name));
            ViewBag.Categories = categories;
            if (str != null)
            {
                ViewData["Error"] = str;
            }
            else ViewData["Error"] = "true";


            return View();
        }
        [HttpPost]
        public IActionResult Register(UserVM userVM)
        {
            var checkEmail = _context.AdminUsers.FirstOrDefault(p => p.Email.Equals(userVM.Email));
            if (checkEmail == null)
            {
                AdminUser user = new AdminUser();
                user.Email = userVM.Email;
                user.Password = MaHoaMatKhau(userVM.Password);
                user.Name = userVM.Name;
               
                user.Role = "Admin";
                _context.AdminUsers.Add(user);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            string mailerr = "Mail đã tồn tại";
            return RedirectToAction("Register", mailerr);
        }

        public IActionResult Login()
        {
            ViewData["LogErorr"] = "true";
            return View();

        }
        [HttpPost]
        public IActionResult Login(User LogUser)
        {
            ViewBag.Admin = "";
            string pass = MaHoaMatKhau(LogUser.Password);
            var user = _context.AdminUsers.FirstOrDefault(p => p.Email.Equals(LogUser.Email) && p.Password == pass);
            var us = _context.AdminUsers.FirstOrDefault(p => p.Email.Equals(LogUser.Email));
            var passw = us.Password;
            if (user != null)
            {
                int id = user.Id;
                HttpContext.Session.SetInt32("AdminId", id);
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["LogErorr"] = "Tài Khoản Hoặc Mật Khẩu không đúng";
                return RedirectToAction("Login");
            }

        }
        public IActionResult Index()
        {
            ViewBag.Admin = "";
            if (HttpContext.Session.GetInt32("AdminId") == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                int id = (int)HttpContext.Session.GetInt32("AdminId");
                ViewBag.Admin = _context.AdminUsers.FirstOrDefault(p=> p.Id == id);
                foreach (var product in _context.Products)
                {

                    if (product.Views == null || product.Views == 0)
                    {
                        product.Views = Random(10000);
                    }
                    if (product.Downloads == null || product.Downloads == 0)
                        product.Downloads = Random(500);
                    if (product.Likes == null || product.Likes == 0)
                        product.Likes = Random(1000);
                    var date = DateTime.Now;
                    if (product.TimeCreate.Value.Year < date.Year)
                        product.TimeCreate = date.AddDays(-2);
                    _context.Products.Update(product);

                }
                _context.SaveChanges();
                var products = _context.Products.ToList();
                return View(products);
            }
            
        }

        public int GetIdProduct()
        {
            int i = 0;
            foreach (var x in _context.Products)
                i = x.Id;
            return i;
        }

        public IActionResult Add ()
        {
            if (HttpContext.Session.GetInt32("AdminId") == null)
            {
                return RedirectToAction("Login");
            }
            int id = (int)HttpContext.Session.GetInt32("AdminId");
            ViewBag.Admin = _context.AdminUsers.FirstOrDefault(p => p.Id == id);
            var categories = _context.Categories.ToList();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            
            return View();
        }

        public int Random (int x)
        {
            Random rd = new Random();
            return rd.Next(1,x);
        }
        [HttpPost]
        public IActionResult Add(Product product, IFormFile FileUrl, IFormFile ImageUrl)
        { //Ham ModelState se kiem tra lai du lieu cua Model duoc truyen tu view qua
            //Ta chi truyen FIle anh vs file qua 2 bien FileUrl ... con model.FileUrl vs cac bien con lai thi chua nhan duoc nen can phai bo kiem tra
            
            ModelState.Remove("File");
            ModelState.Remove("FileImage");
            ModelState.Remove("Category");
            ModelState.Remove("User");
            
            int id = GetIdProduct() + 1;

            if (ImageUrl != null)
            {
                product.FileImage = SaveImage(ImageUrl,id);
            }
            if (FileUrl != null)
            {
                product.File = SaveFile(FileUrl, id);
                product.TypeFile = Path.GetExtension(FileUrl.FileName);
            }
            if (ModelState.IsValid)
            {
                product.User = _context.Users.FirstOrDefault(p => p.Id == 1);
                product.Status = "No Confirm";
                product.UserId = 1;
                product.Views = 0;
                product.Likes = 0;
                product.Downloads = 0;
                product.TimeCreate = DateTime.Now;
                _context.Products.Add(product);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }      
            var categories = _context.Categories.ToList();
            ViewBag.categories = new SelectList(categories, "Id", "Name");
            return RedirectToAction(nameof(Add)); 
             
           
        }

        public IActionResult Update(int id)
        {
            if (HttpContext.Session.GetInt32("AdminId") == null)
            {
                return RedirectToAction("Login");
            }
            int Id = (int)HttpContext.Session.GetInt32("AdminId");
            ViewBag.Admin = _context.AdminUsers.FirstOrDefault(p => p.Id == Id);
            var product = _context.Products.FirstOrDefault(p => p.Id == id);
            var categories = _context.Categories.ToList();
            ViewBag.categories = new SelectList(categories, "Id", "Name");
            return View(product);
        }
        [HttpPost]
        public IActionResult Update(int id, Product product, IFormFile ImageUrl, IFormFile FileUrl) 
        {
            ModelState.Remove("File");
            ModelState.Remove("FileImage");
            ModelState.Remove("Category");
            ModelState.Remove("User");

            
            if(ImageUrl != null)
            {
                product.FileImage = SaveImage(ImageUrl, id);
            }
            if( FileUrl != null)
            {
                product.File = SaveFile(FileUrl, id);
                product.TypeFile = Path.GetExtension(FileUrl.FileName);
            }
           
                var existProduct =  _context.Products.FirstOrDefault(product => product.Id == id);
                if (existProduct != null)
                {
                    existProduct.Name = product.Name;
                    existProduct.Description = product.Description;
                    existProduct.CategoryId = product.CategoryId;
                    existProduct.TimeCreate = product.TimeCreate;
                    existProduct.Price = product.Price;
                    existProduct.File = product.File;
                    existProduct.FileImage = product.FileImage;
                    existProduct.Views = product.Views;
                    existProduct.Likes = product.Likes;
                    existProduct.Downloads = product.Downloads;
                    existProduct.Status = "No Confirm";
                    existProduct.TypeFile = product.TypeFile;
                    _context.Products.Update(existProduct);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
            

            var categories = _context.Categories;
            ViewBag.Categories = new SelectList("categories", "Id", "Name");
            return View(product);

        }
        public string SaveImage(IFormFile Image, int id)
        {
            int index = Image.FileName.IndexOf(".");
            var filename = Image.FileName.Insert(index , "_" + id.ToString());
            var savePath = Path.Combine("wwwroot/Images",filename);
            using (var fileStream = new FileStream(savePath, FileMode.Create))
            {
                Image.CopyTo(fileStream);
            }
            return "/Images/" + filename;
        }
        public string SaveFile(IFormFile FileUrl, int id)
        {
            int index =  FileUrl.FileName.IndexOf(".");
            var filename = FileUrl.FileName.Insert(index , "_" + id.ToString());

Web chia se tai lieu/Web chia se tai lieu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/style.css">
    
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class = "header">
        <div class="header__nav" style="border: 1px solid black;">
            <div class="header__title-name" >𝓜𝔂 𝓓𝓸𝓬𝓾𝓶𝓮𝓷𝓽 </div>
            <div class="header__title-content">Nơi chia sẻ tài liệu miễn phí</div>
        </div>
        <div class="header__nav">
            <div class= "header__nav-list">
                <div class="header__nav-item menu">
                    <div class="tag-link text-color1">Menu</div>
       
                    <ul class="menu-list">
                        @foreach (var item in ViewBag.Categories)
                        {
                            <li><a class="" asp-action="Product" asp-controller="Home" asp-route-id="@item.Id">@item.Name </a></li>
                        }
                    </ul>
                    
                </div>
                
            </div>
            <div class="header__nav-search">
                
                <input id="search" style="margin-right: 0; min-width: none;" type="text" placeholder="tìm kiếm 1 triệu tài liệu">
                @{
                    
                }
                <!-- <a asp-action="Search" asp-controller="Home" asp-route-search=TextChange() style="margin-left: 0;" class="btn btn-info"><i class="bi bi-search"></i></a>-->
                <button style="margin-left: 0;" class="btn btn-info" onclick="Search()"><i class="bi bi-search"></i></button>
                
            </div>
            
            <div class="header__nav-upload">
                @if(ViewData["userId"] == null)
                {
                    <button class="btn1" type="submit" onclick="NoLogin()"><i class="bi bi-upload"></i> Upload</button>
                }else{
                    <a style="text-decoration: none; color: black; font-style: normal;" asp-action="Upload" asp-controller="Home">
                        <button class="btn1" type="submit"><i class="bi bi-upload"></i> Upload</button>
                    </a>
                }
               
                
            </div>    
            <script>

                function Search() {
                    alert("Tesst");
                    var text = document.getElementById("search");
                    var search = text.value;
                    $.ajax({
                        url: "/Home/Search",
                        type: 'POST',
                        data: { search },
                        success: function () {
                            console.log("Hoan Thanh");
                        }
                    })
                    function NoLogin() {
                        alert("Phai dang nhap moi duoc up tai lieu");
                    }
                }
            </script>
            <ul class="header__nav-list" styles="">
                <li class="header__nav-item noitification">
                    <i class="bi bi-bell-fill ">Thong bao</i>
                </li>
                @if(ViewData["userId"] == null)
                {
                    <li class="header__nav-item"><a class="tag-link text-color1" asp-action="Register">Dang Ky</a></li>
                    <li class="header__nav-item"><a class="tag-link text-color1" asp-action="Login">Dang Nhap</a></li>
                }else{
                    <li class="header__nav-item" style="background-color: none; padding: 0px 15px;">Coin: @ViewBag.User.Coin</li>
                    <li class="header__nav-item"> Xin Chào <a class="tag-link text-color1" asp-action="" title="Click vào để đi đến quản lý tài khoản">@ViewBag.User.Name</a></li>
                    <li class="header__nav-item" style="margin-left: 20px;"><a class="tag-link text-color1" asp-action="Logout">Dang Xuất</a></li>
                }
                
                
            </ul>
        </div>
      
    </div>

    <div class="chat">
        
        <div class="icon-mess">
            <a href="https://zalo.me/0815805626"><img src="/Images/zalo-logo-inkythuatso-14-15-05-01.jpg" alt=""></a>
            <img src="/Images/Apple_Messages-512.webp" alt=""> 
        </div>
    </div>
    @RenderBody();
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 py-5 px-sm-3 px-lg-5" style="margin-top: 90px;">
        <div class="row pt-5">
            <div class="col-lg-3 col-md-6 mb-5">

                <h6 class="text-white text-uppercase mt-4 mb-3" style="letter-spacing: 5px;">Theo dõi chúng tôi</h6>
                <div class="d-flex justify-content-start">
                    <a class="btn btn-outline-primary btn-square" href="https://www.facebook.com/phan.tu.167189"><i class="fab fa-facebook-f"></i></a>


                    <a class="btn btn-outline-primary btn-square" href="https://www.instagram.com/quanhan2200/ " /><i class="fab fa-instagram"></i></a>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Link tương tác</h5>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white-50 mb-2" href="https://localhost:44367/#"><i class="fa fa-angle-right mr-2"></i>Trang chủ</a>
                    <a class="text-white-50 mb-2" href="https://www.facebook.com/messages/t/7340758472649420"><i class="fa fa-angle-right mr-2"></i>Group chat</a>
                    <a class="text-white-50 mb-2" href="https://www.facebook.com/phan.tu.16718"><i class="fa fa-angle-right mr-2"></i>FanPage</a>

                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Thông tin hợp tác</h5>
                <p><i class="fa fa-map-marker-alt mr-2"></i>HUTECH UNIVERSITY</p>
                <p><i class="fa fa-phone-alt mr-2"></i>093 451 8248</p>
                <p><i class="fa fa-envelope mr-2"></i>tusuri789@gmail.com</p>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-white border-top py-4 px-sm-3 px-md-5" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="row">
            <div class="col-lg-6 text-center text-md-left mb-3 mb-md-0">
            </div>
        </div>
        <div class="col-lg-6 text-center text-md-right">
            <p class="m-0 text-white-50">
                Designed by <a>WebchiasetailieuTeam</a>
            </p>
        </div>
    </div>
    <!-- Footer End -->

    
   
  </body>
</html>
<!--
                                

-->

Web chia se tai lieu/Web chia se tai lieu/Views/Shared/_Layout1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-info navbar-dark">
        @if(ViewBag.Admin != null){
            <a class="navbar-brand" href="#">@ViewBag.Admin.Name</a>
        }
        
        <div class="col-8">
            <ul class="navbar-nav">
                <li class="nav-item "><a asp-action="Index" asp-controller="AProduct" class="nav-link">Trang chủ</a></li>
                <li class="nav-item "><a asp-action="Index" asp-controller="ACategory" class="nav-link">Danh Mục</a>></li>

            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        @RenderBody();
    </div>

</body>
</html>

Web chia se tai lieu/Web chia se tai lieu/Views/Shared/_commentPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Web_chia_se_tai_lieu.ViewModels.CommentVM;
@{
    var str ="";
}
<div  class="form" style=" border: 1px solid red">
    
    <div class="form-row" style="padding: 10px; border: 1px solid black">
        <label >Nội Dung Bình Luận: </label>
        <textarea id="content" type="text"  class="form-control" ></textarea>
    </div>
    
        <button type="submit" style="align-items:center;"  class="btn btn-success" onclick="Click(TextChange())">Đăng</button>
   
</div>
<script>
    
    function TextChange (){
        var text = document.getElementById("content").value;
        
        return text;
    }

</script>

Web chia se tai lieu/Web chia se tai lieu/Views/Shared/_listcommentPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Web_chia_se_tai_lieu.ViewModels.CommentVM>;

    <style>
        .main{
            width: max;
            margin: 15px 0;
            padding: 10px;
            border: 1px solid black;
            
        }
        .item{
            display: flex;
            gap: 10px;
            margin: 4px 0;
        }
        .comment{

        }
        .comment_detail{
            display: flex;
            gap: 15px;
            width: max;
        }
        .comment_conttent{
            color: black;
            padding-top: 4px;
        }
        img{
            width: 50px;
            height: 50px;

        }
        
        .list{
            display: none;
           
        }
        .icon {
            cursor:pointer;
        }
        
        .icon:active  .list{
            display: block;  
            min-width: 50px;
            background-color: wheat;
            border: 1px soil black;
            padding: 2px 4px 2px 4px;
            left: 0px;
            position: absolute;
            top: 0;
        }
        .list:hover {
            display: block;  
            min-width: 50px;
            background-color: wheat;
            border: 1px soil black;
            padding: 2px 4px 2px 4px;
            left: 0px;
            position: absolute;
            top: 0;
        }

            

        
        .list li:hover{
            background-color: white;
            opacity: 0.7;
            border: 1px soil black;
        }
    </style>

    <div class="main">
        @foreach(var item in Model){

        <div class="item">
            <img src="@item.ImgeUrl" />
            <div class="comment">
                <div class="comment_detail">
                    <a href="#" class="text-decoration-none" style="font-weight: bold;">@item.UserName</a>
                    <span style="font:italic; font-size: 14px;">@item.CreatedDate?.ToString("dd-MM-yyyy")  @item.CreatedDate?.ToString("HH:mm")</span>
                </div>
                <div class="d-flex justify-content-between" style="width: 100%; margin-right: 10px;">
                    <p class="comment_content">@item.Content</p>
                    @if(ViewData["UserId"].ToString() == item.UserId.ToString())
                    {
                        <div class="icon" style="position: relative;">
                            <i class="fas fa-ellipsis-v "></i>
                            <ul class="list">
                                <li onclick="Load_Listcomment_delete(@item.Id)">Xóa</li>
                            </ul>
                        </div>
                    }
                    
                </div>
                
            </div>
            
        </div>
        }
        
    </div>

Web chia se tai lieu/Web chia se tai lieu/Views/Shared/_pagePartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model int;
@{
    string tmp = ViewData["page"].ToString();
    int page = int.Parse(tmp);
    int page_before = page - 2;
}

<style>
    .btn-click{
        background-color: blue;
        font-weight: bold;
    }
</style>
<div class="d-flex justify-content-center ">
    
    @if(Model <= 5 )
    {
        @for (int i = 1; i <= Model; i++)
        {
            if (i == page)
            {
                <button id="page_start" style="padding: 0 5px;" class="btn " type="submit" onclick="Click(event, @i)">@i</button>
            }
            else
            {
                <button class="btn" style="padding: 0 5px;" type="submit" onclick="Click(event, @i)">@i</button>
            }
        }
        <div> ... </div>
        <button class="btn" style="padding: 0 5px;" type="submit" onclick="Click(event,@Model)">@Model</button>
    }
    else
    {
        if(page == 1)
        {
            @for (int i = 1; i <= 5; i++)
            {
                if (i == page)
                {
                    <button id="page_start" style="padding: 0 5px;" class="btn " type="submit" onclick="Click(event, @i)">@i</button>
                }
                else
                {
                    <button class="btn" style="padding: 0 5px;" type="submit" onclick="Click(event, @i)">@i</button>
                }
            }
            <div> ... </div>
            <button class="btn" style="padding: 0 5px;" type="submit" onclick="Click(event,@Model)">@Model</button>
        }
        else
        {
             int page_next = ((page + 5)> Model)? Model : page+ 5;
        int t = page_next;
        @for(int i = page - 2; i<= page_next; i++)
        {
            if( i == page)
            {
                <button id="" class="btn btn-success" style="padding: 0 5px;" type="submit" onclick="Click(event,@i)">@i</button>
            }
            else
            {
                <button class="btn" style="padding: 0 5px;" type="submit" onclick="Click(event,@i)">@i</button>
            }
        }
        <div> ... </div>
        <button class="btn" style="padding: 0 5px;" type="submit" onclick="Reload_product(@Model)">@Model</button>
        }
       
    }

    <script>
        /*
        function Click() {

            const elements = document.getElementsByClassName("btn");
            for (let element of elements) {
                element.addEventListener('click', function () {
                    element.classList.add("btn-click");
                    for (let element1 of elements) {
                        if (element1.classList.contains("btn-click") && element1 !== this) {
                            element1.classList.remove("btn-click");
                        }
                    }
                });
            }
        }
        */
        const page_start = document.getElementById("page_start");
        page_start.classList.add("btn-success");

        function Click(event, i) {
            Reload_product(i);
            
            event.target.classList.add("btn-success");
            const elements = document.getElementsByClassName("btn");
            for (let element of elements) {
                if (element !== event.target && element.classList.contains("btn-success")) {
                    element.classList.remove("btn-success");
                }
            }
            if(i % 5 == 0)
                Reload_Pages(i);
        }
        

    </script>
</div>